name: PouchDB
description: PouchDB, the JavaScript Database that Syncs!
url: http://pouchdb.com
highlighter: rouge
markdown: redcarpet
baseurl:
version: 5.3.2
paginate: 5
paginate_path: "blog/page:num"
github:
  repository_url: https://github.com/pouchdb/pouchdb
collections:
  guides:
    output: true
